apiVersion: v1
kind: Pod
metadata:
  name: nginx-kubedog-example
  namespace: kubedog-example
  labels:
    tier: backend
spec:
  containers:
  - name: hello
    image: busybox:1.28
    command: ['sh', '-c', 'echo "Hello, Kubedog!" && sleep 3600']
  restartPolicy: OnFailure