name: CI
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  build:
    name: build-test-coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: ^1.19
      id: go
    - uses: actions/checkout@v4
    - run: make build
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.txt # optional
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
